language: python

os: linux
dist: focal

python:
    - "3.11"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8
  - coverage run manage.py test

after_script:
  - coveralls

  
deploy:
  provider: elasticbeanstalk
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  region: "us-west-2"
  app: "TutorNYU-dev-branch"
  env: "app-env"
  bucket_name: "elasticbeanstalk-us-west-2-381492260474"
  on:
      branch: develop

deploy:
  provider: elasticbeanstalk
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  region: "us-west-2"
  app: "TutorNYU-production"
  env: "production-env"
  bucket_name: "elasticbeanstalk-us-west-2-381492260474"
  on:
      branch: master