language: python

os: linux
dist: focal

python:
    - "3.11"

install:
  - pip install -r requirements.txt
  - pip install pillow

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8
  - coverage run manage.py test --noinput
  - if [ "$TRAVIS_BRANCH" = "master" ]; then cp .ebextensions/django.config.master .ebextensions/django.config; fi
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then cp .ebextensions/django.config.dev .ebextensions/django.config; fi
  - cat .ebextensions/django.config
  
after_script:
  - coveralls
  
deploy:
  - provider: elasticbeanstalk
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    region: "us-west-2"
    app: "TutorNYU-dev-branch"
    env: "app-env"
    bucket_name: "elasticbeanstalk-us-west-2-381492260474"
    on:
        branch: develop
        
  - provider: elasticbeanstalk
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    region: "us-west-2"
    app: "TutorNYU-production"
    env: "production-env"
    bucket_name: "elasticbeanstalk-us-west-2-381492260474"
    on:
        branch: master
