# Generated by Django 5.0.2 on 2024-02-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TutorRegister", "0002_usertype_rename_school_profilet_major"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserType",
        ),
    ]
