# Generated by Django 5.0.2 on 2024-03-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TutorRegister", "0005_usertype_has_profile_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilet",
            name="salary_max",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profilet",
            name="salary_min",
            field=models.IntegerField(default=0),
        ),
    ]
