# Generated by Django 5.0.2 on 2024-03-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TutorRegister", "0007_profiles_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilet",
            name="image",
            field=models.ImageField(
                default="images/profile_icon.png", upload_to="images/"
            ),
        ),
    ]
