# Generated by Django 5.0.2 on 2024-03-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TutorRegister", "0009_tutoringsession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutoringsession",
            name="time",
        ),
        migrations.AddField(
            model_name="tutoringsession",
            name="end_time",
            field=models.TimeField(default="12:00:00"),
        ),
        migrations.AddField(
            model_name="tutoringsession",
            name="start_time",
            field=models.TimeField(default="12:00:00"),
        ),
    ]
