# Generated by Django 5.0.2 on 2024-03-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "TutorRegister",
            "0010_remove_tutoringsession_time_tutoringsession_end_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringsession",
            name="status",
            field=models.TextField(default="Pending"),
        ),
    ]
