# Generated by Django 5.0.2 on 2024-03-26 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TutorRegister", "0011_tutoringsession_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringsession",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.CreateModel(
            name="TutorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_date", models.DateField(auto_now_add=True)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
                ("review", models.TextField()),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
