# Generated by Django 5.0.2 on 2024-03-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TutorRegister", "0012_favorite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="student",
            new_name="student_id",
        ),
        migrations.RenameField(
            model_name="favorite",
            old_name="tutor",
            new_name="tutor_id",
        ),
    ]
