# Generated by Django 5.0.2 on 2024-03-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TutorRegister", "0012_tutoringsession_attachment_tutorreview"),
        ("TutorRegister", "0013_rename_student_favorite_student_id_and_more"),
    ]

    operations = []
