# Generated by Django 5.0.2 on 2024-03-31 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TutorRegister", "0013_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringsession",
            name="reviewed_by_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tutorreview",
            name="tutoring_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_reviews",
                to="TutorRegister.tutoringsession",
            ),
        ),
    ]
