# Generated by Django 5.0.2 on 2024-03-31 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TutorRegister", "0012_chatsession_message"),
        ("TutorRegister", "0014_tutoringsession_reviewed_by_student_and_more"),
    ]

    operations = []
