# Generated by Django 5.0.2 on 2024-04-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TutorRegister", "0016_profilet_qualified_profilet_transcript_post_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilet",
            name="qualified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
