# Generated by Django 5.0.2 on 2024-04-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TutorRegister", "0017_alter_profilet_qualified"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringsession",
            name="meeting_link",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
