# Generated by Django 5.0.2 on 2024-04-08 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TutorRegister", "0018_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_replies",
                to="TutorRegister.post",
            ),
        ),
    ]
