# Generated by Django 5.0.2 on 2024-04-08 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TutorRegister", "0017_alter_profilet_qualified"),
        ("TutorRegister", "0019_alter_reply_post"),
    ]

    operations = []
