# Generated by Django 5.0.2 on 2024-04-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TutorRegister", "0018_tutoringsession_meeting_link"),
        ("TutorRegister", "0020_merge_20240408_0439"),
    ]

    operations = []
