# Generated by Django 5.0.2 on 2024-04-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TutorRegister", "0023_post_topics_react"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="topics",
            field=models.CharField(blank=True, verbose_name=models.CharField()),
        ),
    ]
